# Generated by Django 3.0.3 on 2020-09-08 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('amount', models.FloatField()),
                ('balance', models.FloatField()),
            ],
            options={
                'db_table': 'financial_ledger',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('invoice_total', models.FloatField()),
                ('status', models.CharField(blank=True, choices=[('sent, sent', 'Sent'), ('paid', 'paid'), ('overdue', 'overdue'), ('created', 'created')], default='created', max_length=20)),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
    ]
