# Generated by Django 3.0.3 on 2020-09-08 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('invoice', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_invoices', to='user.Customer'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_invoices', to='order.Order'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sales_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_agent_invoices', to='user.SalesAgent'),
        ),
        migrations.AddField(
            model_name='financialledger',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_ledgers', to='user.Customer'),
        ),
        migrations.AddField(
            model_name='financialledger',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_ledgers', to='order.Order'),
        ),
    ]
