# Generated by Django 3.0.3 on 2020-09-07 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('order', '0002_auto_20200907_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('ordered, ordered', 'Ordered'), ('accepted', 'accepted'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='ordered', max_length=20),
        ),
    ]
