# Generated by Django 3.0.3 on 2020-09-08 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('order', '0006_auto_20200908_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to='user.Customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='sales_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_agent_orders', to='user.SalesAgent'),
        ),
    ]
